[pytest]
DJANGO_SETTINGS_MODULE = config.test_settings
python_files = tests.py test_*.py *_tests.py
addopts = -ra -p no:cacheprovider
norecursedirs = .git .venv venv env __pycache__ .pytest_cache pytest-cache-files-*
